// <auto-generated />
using System;
using Lazcat.Blog.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lazcat.BlogApiService.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20210131133720_Add column to article table")]
    partial class Addcolumntoarticletable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Articles.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EditTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Title");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.HashTags.ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<Guid>("HashTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArticleId", "HashTagId");

                    b.HasIndex("HashTagId");

                    b.ToTable("ArticleTags");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.HashTags.HashTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HashTags");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sender")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Messages.ReplyMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RepliedMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReplyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("RepliedMessageId");

                    b.ToTable("ReplyMessages");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Articles.Article", b =>
                {
                    b.HasOne("Lazcat.Blog.Models.Domain.Categories.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.HashTags.ArticleTag", b =>
                {
                    b.HasOne("Lazcat.Blog.Models.Domain.Articles.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lazcat.Blog.Models.Domain.HashTags.HashTag", "HashTag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("HashTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("HashTag");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Messages.Message", b =>
                {
                    b.HasOne("Lazcat.Blog.Models.Domain.Articles.Article", "Article")
                        .WithMany("Messages")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Messages.ReplyMessage", b =>
                {
                    b.HasOne("Lazcat.Blog.Models.Domain.Messages.Message", "Message")
                        .WithMany("ReplyMessages")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lazcat.Blog.Models.Domain.Messages.Message", "RepliedMessage")
                        .WithMany()
                        .HasForeignKey("RepliedMessageId");

                    b.Navigation("Message");

                    b.Navigation("RepliedMessage");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Articles.Article", b =>
                {
                    b.Navigation("ArticleTags");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Categories.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.HashTags.HashTag", b =>
                {
                    b.Navigation("ArticleTags");
                });

            modelBuilder.Entity("Lazcat.Blog.Models.Domain.Messages.Message", b =>
                {
                    b.Navigation("ReplyMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
